Alex first contribution
breadlesscode/neos-nodetypes-folder pull request #20
Opened 2023-01-14 17:43 UTC by alexander-nitsche

Hi Marvin,

this pull request is about some small beautifications that i did while starting to use your package for folder creation in my Neos 7 instance. They are about streamlining of wording and backend layout. Thanks for your efforts!

Greetings
Alex

2023-01-14 17:48 UTC, alexander-nitsche commented
It looks like this on my Linux machine:
![folder_backend_layout](https://user-images.githubusercontent.com/20297232/212487714-94d67424-2174-4bea-aff7-175ad85c7eab.png)

2023-01-15 14:13 UTC, alexander-nitsche commented
Added prefixed, unique CSS class names and a simplified, common template path. PR is ready for further processing.

2023-01-19 09:48 UTC, breadlesscode approved these changes
Awesome, thanks! ❤️ 

I will merge it soon

2023-01-19 09:55 UTC, breadlesscode requested changes

2023-01-19 09:55 UTC, breadlesscode commented on Resources/Private/Templates/Folder.html
> +<div id="breadlesscode-node-types-folder">
Can we use AFX instead of Fluid?

2023-01-19 09:58 UTC, alexander-nitsche commented on Resources/Private/Templates/Folder.html
> +<div id="breadlesscode-node-types-folder">
Is AFX available for Neos 4?

2023-01-20 12:19 UTC, breadlesscode commented on Resources/Private/Templates/Folder.html
> +<div id="breadlesscode-node-types-folder">
Oh yes, your right. Thanks :)

2023-01-20 12:20 UTC, merged